version: '3.8'

services:
  web:
    build: .
    ports:
      - "3001:3001"
    volumes:
      - .:/app
    environment:
      - RAILS_ENV=development
      - REDIS_URL=redis://redis:6379/0
      - DATABASE_URL=postgresql://postgres:example@db:5432/app_development
    depends_on:
      - db
      - redis
    command:
      - /bin/sh
      - -c
      - |
        rm -rf ./tmp/pids/server.pid
        bundle exec rails db:migrate
        bundle exec rails s -b 0.0.0.0 -p 3001
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
  sidekiq:
    build: .
    command: bundle exec sidekiq
    volumes:
      - .:/app
    environment:
      - RAILS_ENV=development
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - db
      - redis
  db:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: app_development
